name: release-plz

on:
  push:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  release-plz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dtolnay/rust-toolchain@stable

      - name: release-pr
        uses: release-plz/action@v0.5
        with:
          command: release-pr
          manifest_path: src-tauri/Cargo.toml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: release
        uses: release-plz/action@v0.5
        with:
          command: release
          manifest_path: src-tauri/Cargo.toml
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
